### ISSUE TITLE
FEAGI ends with error on its own

### ISSUE THREAD

**Issue by Kakcalu13** [feagi/feagi-core#16]
FEAGI was running in background as I was setting things up include screenshot. The FEAGI suddenly stopped and display the error below:
`>>> Burst duration: 0:00:00.102987 550 --- ---- ---- ---- ---- ---- ----
Traceback (most recent call last):
  File "main.py", line 60, in <module>
    burst_engine.burst_manager()
  File "/home/bwuk/feagi-core/src/npu/burst_engine.py", line 391, in burst_manager
    burst()
  File "/home/bwuk/feagi-core/src/npu/burst_engine.py", line 347, in burst
    consciousness_manager()
  File "/home/bwuk/feagi-core/src/npu/burst_engine.py", line 53, in consciousness_manager
    if datetime.now() - runtime_data.last_ipu_activity > runtime_data.parameters['IPU']['idle_threshold']:
TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'str'
(environName) bwuk@robots:~/feagi-core/src$ `

Is it something that I missed to download?

**Comment by erm156** [comment]
I added a fix for this bug to the existing `feature-lidar-ipu` branch. If it'd be better to keep things separate, I will add the fix in a different branch so it can be merged in by itself.

**Comment by erm156** [comment]
closed via #17
